{{- range $namespace, $details := .Values.secrets }}
{{- range $secrets := $details }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ $secrets.name }}
  namespace: {{ $namespace }}
type: {{ $secrets.type | default "Opaque" }}
spec: 
  itemPath: {{ $secrets.item }}
{{- end }}
{{- end }}